export const metadata = {
    title: "Auth",
    description: "Generated by Next.js",
};
export default function ForgotPassword(){
    return <div>
        <h1 className="text-center">Fortgot Your Password</h1>
    </div>;
}