import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "next app",
    template: "%s | Next App",
  },
  description: "Generated by Next App",
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:"gray",padding: "0.5rem"}}>
          Navbar
        </header>
        {children}
        <footer style={{backgroundColor:"lightblue",padding: "0.5rem"}}>
          Footer
        </footer>
      </body>
    </html>
  )
}
