export const metadata = {
    title: "Auth",
    description: "Generated by Next.js",
};
export default function Login(){
    return <div>
        <div className="">
            <div className="text-center">
                <h1 className="text-2xl font-bold">Sign In</h1>
                <span>to continue to your account please sign in</span>
            </div>
            <form action="#" className="my-5 flex flex-col items-center">
                <label htmlFor="username" className="">username</label>
                <input type="text" className="form-input" />
                <label htmlFor="password" className="">password</label>
                <input type="text" className="form-input" />
                <button className="btn-transparent">Sign in</button>
            </form>
        </div>
    </div>;
}