import Link from "next/link";

export const metadata = {
    title: "Auth",
    description: "Generated by Next.js",
};
export default function Login(){
    const placeUsername = () => {
    }
    return <div className="">
        <div className="mt-20">
            <div className="alert alert-danger"></div>
            <div className="text-center py-5">
                <h1 className="text-2xl font-bold">Sign In</h1>
                <span>to continue to your account please sign in</span>
            </div>
            <form action="#" className="my-10 login-form flex flex-col justify-center items-center">
                {/* <label htmlFor="username" className="">username</label> */}
                <input type="text" className="md:w-100 sm:w-100 lg:w-3/12 form-input" placeholder="username..."/>
                <input type="password" className="form-input md:w-100 sm:w-100 lg:w-3/12" placeholder="password" />
                <button className="btn-transparent">Sign in</button>
                <div className="mt-5">
                    <p>please accept 
                    <Link href="./register" className="ms-2 text-blue-300 hover:text-blue-500">privacy & policy of use</Link> 
                    </p>
                    <p>Do not have an account ? 
                        <Link href="./register" className="ms-2 hover:text-sky-400 underline">lets create one</Link> 
                        <p className="text-center"><Link href="./forgot-password" className="text-red-500">forgot password?</Link></p>
                    </p>
                    
                </div>
            </form>
        </div>
    </div>;
}