export const metadata = {
    title: "Profile",
    description: "Generated by Next.js",
};
export default function Profile(){
   return (<>
   <div className="section-container">
    <div className="text-center">
       <h1 className="font-bold text-2xl">Profile</h1>
       <small className="p-0 m-0">[this is the description section of the profile]</small>
    </div>
   </div>
   </>);
}