import Image from "next/image"
import { FaEye, FaHeart} from "react-icons/fa";
import { IoAdd } from "react-icons/io5";
import { FiEdit } from "react-icons/fi";
import { VscGitPullRequestCreate } from "react-icons/vsc";
export const metadata = {
    title: "Blog",
    description: "Generated by Next.js",
};
export default function Blog(){
    return (<>
        <div className="section-container">
            <div className="text-center my-10">
                <p className="text-2xl font-bold">Post Title</p>
                <p className="text-sm">post descriptions</p>
            </div>
            <div className="grid xl:grid-cols-5 lg:grid-cols-5 sm:grid-cols-1 md:grid-cols-2 gap-3">
                <div className="xl:col-span-2 sm:grid-cols-1 post-image bg-gray-600 h-48 animate-pulse">
                    <div className="border border-gray-600 rounded p-5">
                        <Image src="/next.svg" alt="post image" width={400} height={400}></Image>
                    </div>
                </div>
                <div className="xl:col-span-3 sm:grid-cols-1 post-descriptions h-48">
                    <div className="border border-gray-600 rounded p-5 animate-pulse">
                        <p className="text-xl h-5 bg-gray-600 font-bold rounded"></p>
                        <p className="text-sm h-2 bg-gray-600 rounded ms-1 mt-5"></p>
                        <p className="text-sm h-2 bg-gray-600 rounded m-1"></p>
                        <p className="text-sm h-2 bg-gray-600 rounded m-1"></p>
                        <p className="text-sm h-2 bg-gray-600 rounded m-1"></p>
                        <p className="text-sm h-2 bg-gray-600 rounded mt-5"></p>
                    </div>
                </div>
            </div>
            {/* post display rendering page start */}
            <div className="grid xl:grid-cols-5 lg:grid-cols-5 sm:grid-cols-1 md:grid-cols-2">
                <div className="xl:col-span-2 sm:grid-cols-1 m-auto p-5">
                    <div className="text-3xl font-bold mb-4">
                        <h1>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetu</h1>
                    </div>
                    <div className="font-light">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                            Donec suscipit nunc in diam maximus, quis porta lorem condimentum. 
                            Vivamus vestibulum sagittis arcu eget fermentum. In gravida nisi eu eleifend 
                            finibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere 
                            cubilia curae; Pellentesque dignissim quam ac lectus cursus blandit. Pellentesque 
                            habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin 
                            aliquet finibus lectus, at feugiat risus cursus eu. Sed sodales diam facilisis finibus 
                            varius. Aliquam congue nibh vitae orci congue pharetra sit amet vitae odio. Vestibulum ante 
                            ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus eu diam vel 
                            arcu dignissim porttitor. Integer posuere bibendum augue viverra commodo. Curabitur tortor neque, 
                            ullamcorper eget ligula ac, suscipit vestibulum ex. Vestibulum facilisis rhoncus velit in sagittis. 
                            Nam pulvinar quis sem at venenatis. Donec quis metus a justo auctor ornare.
                        </p>
                        <div className="mt-5 flex">
                            <p className="text-gray-500">updated at: Jun 05, 2024</p>
                            <p className="text-gray-500 ml-5 my-auto"><FaEye className="text-xl inline pb-1"/> 534,523,32</p>
                            <p className="hover:text-rose-600 duration-300 ml-5"><FaHeart className=" text-xl inline pb-1"/></p>
                        </div>
                    </div>
                </div>
                <div className="xl:col-span-2 sm:grid-cols-1 bg-gradient-to-b from-slate-950 to-slate-800">
                    <div className="">
                    <Image src="../idea.svg" width={500} height={300} className="m-auto p-0" alt="post image"></Image>
                    </div>
                </div>
                <div className="bg-gradient-to-b from-slate-900 to-slate-800">
                    <div className="p-5">
                        <h1 className="text-xl font-bold">Menu</h1>
                        <ul className="mt-5">
                            <li className="mb-5">
                                <span className="bg-cyan-500 rounded-full pb-1">
                                    <IoAdd className="text-xl inline"/>
                                </span>  <span className="anchor-link ml-1">Create Post</span>
                            </li>
                            <li className="mb-5">
                                <FiEdit className="text-xl inline mr-2"/>
                                <span className="anchor-link">Update Post</span>
                            </li>
                            <li className="mb-5">
                                <VscGitPullRequestCreate className="inline text-xl mr-2"/>
                                <span className="anchor-link">Request to join the community</span>
                            </li>
                            
                        </ul>
                    </div>
                </div>
            </div>
            {/* post display rendering page end */}
        </div>
    </>);
}